/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package modAtendimento;

/**
 *
 * @author Jenny
 */
public class FormAtendimento extends javax.swing.JFrame {

    /**
     * Creates new form FormAtendimento
     */
    public FormAtendimento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblOperador = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        txtPesquisa1 = new javax.swing.JTextField();
        btnPesquisa1 = new javax.swing.JButton();
        txtPesquisa2 = new javax.swing.JTextField();
        btnPesquisa2 = new javax.swing.JButton();
        txtPesquisa3 = new javax.swing.JTextField();
        btnPesquisa3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblOperador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "Nº Matrícula", "Nome", "Nº Habilitação", "Categoria", "Situação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOperador.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblOperador);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 704, 100));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, 799, 10));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Atendimento");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        txtPesquisa1.setText("Número da Viatúra");
        txtPesquisa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisa1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPesquisa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 139, -1));

        btnPesquisa1.setText("Pesquisar");
        btnPesquisa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisa1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 80, -1));

        txtPesquisa2.setText("Nome do Agente");
        txtPesquisa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisa2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPesquisa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 139, -1));

        btnPesquisa2.setText("Pesquisar");
        btnPesquisa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisa2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 80, -1));

        txtPesquisa3.setText("Código da Ocorrência");
        getContentPane().add(txtPesquisa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 139, -1));

        btnPesquisa3.setText("Pesquisar");
        btnPesquisa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisa3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisa1ActionPerformed

    private void btnPesquisa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisa2ActionPerformed

    private void txtPesquisa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisa2ActionPerformed

    private void btnPesquisa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisa3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisa3ActionPerformed

    private void txtPesquisa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisa1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAtendimento().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisa1;
    private javax.swing.JButton btnPesquisa2;
    private javax.swing.JButton btnPesquisa3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblOperador;
    private javax.swing.JTextField txtPesquisa1;
    private javax.swing.JTextField txtPesquisa2;
    private javax.swing.JTextField txtPesquisa3;
    // End of variables declaration//GEN-END:variables
}
